/**
 * @file rune_minigame.hpp
 * @brief Rune minigame public interface.
 * @details
 * This module implements a small drag-to-touch minigame where the player must
 * touch a sequence of runes in array order (0 -> 1 -> ... -> N-1).
 *
 * Behaviour summary:
 * - `Init()` allocates rune data and creates meshes used for rendering:
 *     - `runeMesh` (untouched visual)
 *     - `runeTouchedMesh` (touched visual)
 *     - `screenMesh` (background)
 *     - `lineMesh` (unit quad used to draw connecting lines)
 *   `Init()` also places runes with a minimum inter-rune distance enforced
 *   (see `RUNE_MIN_DISTANCE` in the implementation).
 *
 * - `Update()` (called each frame) performs input and game logic:
 *     - Reads the current mouse cursor and converts screen coords to world
 *       coordinates before use.
 *     - Only the next untouced rune in array order may be touched. Hovering
 *       over any other untouched rune while holding will reset the sequence.
 *     - The player starts the sequence by clicking on rune 0. While the mouse
 *       button is held, touching the next rune advances the sequence.
 *     - Releasing the mouse before completion resets all touched flags.
 *     - When the final rune is touched the minigame is marked `complete` and
 *       touched state (and connecting lines) persist until explicitly reset.
 *
 * - `Draw()` renders:
 *     - Background (`screenMesh`).
 *     - A connecting polyline composed of quads between successive touched
 *       runes (drawn in order). While the player is holding and the game is
 *       not complete, a trailing line is drawn from the last touched rune to
 *       the current mouse position. Lines are generated by scaling/rotating a
 *       unit quad (`lineMesh`) between two points.
 *
 * - `Free()` releases allocated memory and graphics resources and resets
 *   runtime flags.
 *
 * Notes:
 * - The implementation uses a small helper `isMouseOverRune()` to test
 *   hitboxes using `RUNE_SIZE`.
 * - Debug output is gated behind a `static const bool debug` flag in the .cpp.
 * - Coordinate conversion (screen ? world) uses `screenCoordsToWorldCoords()`
 *   provided by `utilities.cpp`.
 */

#ifndef RUNE_MINIGAME_HPP
#define RUNE_MINIGAME_HPP

#include "AEEngine.h"

namespace RuneMinigame
{
	/**
	 * @brief Represents a single rune in the minigame.
	 *
	 * position: World-space center position for rendering and hit tests.
	 * touched:  True when the rune has been successfully touched in sequence.
	 */
	struct Rune
	{
		AEVec2 position;         ///< World position of the rune
		bool touched = false;    ///< Whether the rune has been touched by the player
	};

	void Load();

	/**
	 * @brief Initialize the minigame.
	 * @details Allocates rune array, generates positions (enforcing a minimum
	 *          spacing between runes), creates the meshes used for both rune
	 *          sprites and the connecting line, and resets runtime flags.
	 */
	void Init();

	/**
	 * @brief Per-frame update.
	 * @details Handles input, sequence ordering, hit detection and reset
	 *          conditions. Converts mouse screen coordinates to world
	 *          coordinates before performing hit tests. Advances the sequence
	 *          only when the next rune in order is hovered while holding the
	 *          mouse; hovering an incorrect rune resets the sequence. Marks
	 *          the minigame complete when all runes are touched in order.
	 */
	void Update();

	/**
	 * @brief Render the minigame.
	 * @details Draws the background, runes (touched/untouched visuals) and the
	 *          connecting lines between successive touched runes. While the
	 *          player is holding (and the sequence is not complete), draws a
	 *          trailing line from the last touched rune to the mouse.
	 */
	void Draw();

	/**
	 * @brief Release all resources.
	 * @details Frees the rune array and all vertex meshes created by Init()
	 *          (rune meshes, screen mesh, and the line mesh) and resets state
	 *          flags (hold/complete).
	 */
	void Free();

	void Unload();
}

#endif // RUNE_MINIGAME_HPP